name: CI DevOps 2025

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Build and test with Maven
      run: |
        cd simple-api-student-main
        mvn clean verify

    - name: Build image and push backend
      uses: docker/build-push-action@v6
      with:
        context: simpleapi
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api-backend:latest
        push: ${{ github.ref == 'refs/heads/main' }}

    - name: Build image and push backend
      uses: docker/build-push-action@v6
      with:
        context: database
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api-backend:latest
        push: ${{ github.ref == 'refs/heads/main' }}


    - name: Build image and push backend
      uses: docker/build-push-action@v6
      with:
        context: http-server
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api-backend:latest
        push: ${{ github.ref == 'refs/heads/main' }}

    - name: SonarCloud Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        cd simple-api-student-main
        mvn sonar:sonar \
          -Dsonar.organization=hammoutid \
          -Dsonar.projectKey=HammoutiD_Devops \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN
